# Generated by Django 4.2.7 on 2025-08-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='total_tests_taken',
        ),
    ]
