# Generated by Django 4.2.7 on 2025-08-15 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_studyplan_aianalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_xp', models.IntegerField(default=0)),
                ('current_level', models.IntegerField(default=1)),
                ('level_title', models.CharField(default='Yangi boshlovchi', max_length=100)),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('last_test_date', models.DateField(blank=True, null=True)),
                ('unlocked_achievements', models.JSONField(default=list)),
                ('achievement_progress', models.JSONField(default=dict)),
                ('total_tests_completed', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('category_mastery', models.JSONField(default=dict)),
                ('preferred_study_time', models.CharField(blank=True, choices=[('morning', 'Ertalab'), ('afternoon', 'Tushdan keyin'), ('evening', 'Kechqurun'), ('night', 'Tunda')], max_length=20)),
                ('active_challenges', models.JSONField(default=list)),
                ('completed_challenges', models.JSONField(default=list)),
                ('weekly_tests', models.IntegerField(default=0)),
                ('monthly_tests', models.IntegerField(default=0)),
                ('improvement_rate', models.FloatField(default=0.0)),
                ('earned_badges', models.JSONField(default=list)),
                ('current_title', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Progress',
                'verbose_name_plural': 'User Progress Records',
            },
        ),
    ]
