# Generated by Django 4.2.7 on 2025-08-16 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('M', 'M - Mototsikl'), ('A1', 'A1 - Engil mototsikl'), ('A', 'A - Mototsikl'), ('B1', "B1 - Uch g'ildirakli transport"), ('B', 'B - Yengil avtomobil'), ('C1', 'C1 - Engil yuk mashinasi'), ('C', 'C - Yuk mashinasi'), ('D1', 'D1 - Kichik avtobus'), ('D', 'D - Avtobus'), ('BE', 'BE - B + tirkama'), ('C1E', 'C1E - C1 + tirkama'), ('CE', 'CE - C + tirkama'), ('D1E', 'D1E - D1 + tirkama'), ('DE', 'DE - D + tirkama')], max_length=10, unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('fact', models.TextField()),
                ('order', models.IntegerField(unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='license_categories/')),
            ],
            options={
                'verbose_name_plural': 'Driving Licenses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LicenseEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.drivinglicense')),
            ],
        ),
        migrations.CreateModel(
            name='UserSafari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_correct_answers', models.IntegerField(default=0)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('journey_started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('current_license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_users', to='quiz.drivinglicense')),
                ('licenses_earned', models.ManyToManyField(related_name='holders', through='quiz.LicenseEarned', to='quiz.drivinglicense')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Safari',
                'verbose_name_plural': 'User Safaris',
            },
        ),
        migrations.AddField(
            model_name='licenseearned',
            name='safari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.usersafari'),
        ),
        migrations.AlterUniqueTogether(
            name='licenseearned',
            unique_together={('safari', 'license')},
        ),
    ]
