# Generated by Django 4.2.7 on 2025-08-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_drivinglicense_licenseearned_usersafari_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='licenseearned',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='licenseearned',
            name='license',
        ),
        migrations.RemoveField(
            model_name='licenseearned',
            name='safari',
        ),
        migrations.RemoveField(
            model_name='usersafari',
            name='current_license',
        ),
        migrations.RemoveField(
            model_name='usersafari',
            name='licenses_earned',
        ),
        migrations.RemoveField(
            model_name='usersafari',
            name='user',
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('ticket', 'Bilet'), ('category', 'Kategoriya'), ('general', 'Umumiy Test')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='testresult',
            name='variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DrivingLicense',
        ),
        migrations.DeleteModel(
            name='LicenseEarned',
        ),
        migrations.DeleteModel(
            name='UserSafari',
        ),
    ]
