# Generated by Django 4.2.7 on 2026-03-27 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_apiconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiconfig',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='apiconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='apiconfig',
            name='name',
        ),
        migrations.RemoveField(
            model_name='apiconfig',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='last_daily_reset',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='priority',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='apiconfig',
            name='used_tokens_daily',
            field=models.IntegerField(default=0),
        ),
    ]
