# Generated by Django 6.0.2 on 2026-06-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_apiconfig_options_remove_apiconfig_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PWASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Avtotest', max_length=100)),
                ('short_name', models.CharField(default='Avtotest', max_length=30)),
                ('description', models.CharField(blank=True, default='Haydovchilik guvohnomasi tayyorgarlik platformasi', max_length=200)),
                ('theme_color', models.CharField(default='#667eea', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('icon_192', models.ImageField(blank=True, null=True, upload_to='pwa/')),
                ('icon_512', models.ImageField(blank=True, null=True, upload_to='pwa/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'PWA Sozlama',
                'verbose_name_plural': 'PWA Sozlamalar',
            },
        ),
    ]
