# Generated by Django 4.2.7 on 2025-08-14 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationContent',
        ),
    ]
